# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stefano Mondino
subtitle: "stuff about Swift"
name: "Stefano Mondino"
title_separator: "|"
email: stefano.mondino.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog about Swift development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stefanomondino.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: puntoste
github:
  username:  puntoste

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
search: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

collections: 
  speaking: 
    output: true
    permalink: /:collection/:path

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true
      author_profile: true
      related: true
      tags: true
      layout: single
      share: true
      comments: true
  # _speaking
  - scope:
      path: ""
      type: speaking
    values:
      layout: single
      read_time: false
      author_profile: false
      share: true
      comments: false

author:
  name: Stefano Mondino
  avatar: /assets/images/avatar.jpg
  bio: "I like Swift coding more than I should. Currently Mobile Platform Leader @Synesthesia srl"
  location: "Torino, Italy"
  links: 
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/puntoste"
  - label: "Github"
    icon: "fab fa-fw fa-github-square"
    url: "https://github.com/stefanomondino"

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include: 
  - "_pages"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# analytics:
#   provider: "google-universal"
#   google:
#     tracking_id: "G-0W8YV4KHT2"
#     anonymize_ip: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
